### ISSUE TITLE
Error when generating an object from a net: AttributeError: 'list' object has no attribute 'xy'

### ISSUE THREAD

**Issue by philippwulff** [patmalcolm91/SumoNetVis#36]
I want to convert my sumo net file into a .obj file.

This is my code:

```
import SumoNetVis

path = "map_name.net.xml"

net = SumoNetVis.Net(path)

# Save a network as an OBJ file
with open("map_name.obj", "w") as f:
    f.write(net.generate_obj_text())
```

However, I receive this error:

```
/home/marcel/anaconda3/envs/pycharm_env/bin/python /home/marcel/Documents/test_data_pw/carla_map_prep/net_to_obj_script.py
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -158180483#2_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -25801580#0_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -33280103#2_2
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -402154210_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:528: UserWarning: Can't generate stopline geometry for lane -643314345_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane 158180483#2_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
Traceback (most recent call last):
  File "/home/marcel/Documents/test_data_pw/carla_map_prep/net_to_obj_script.py", line 12, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py", line 1003, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py", line 407, in get_markings_as_3d_objects
    obj = marking.get_as_3d_object(z=z, extrude_height=extrude_height, include_bottom_face=include_bottom_face)
  File "/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py", line 230, in get_as_3d_object
    oriented_shape = MultiPolygon([orient(shape)])
  File "/home/marcel/anaconda3/envs/pycharm_env/lib/python3.8/site-packages/shapely/geometry/polygon.py", line 396, in orient
    if signed_area(ring)/s >= 0.0:
  File "/home/marcel/anaconda3/envs/pycharm_env/lib/python3.8/site-packages/shapely/algorithms/cga.py", line 6, in signed_area
    xs, ys = ring.coords.xy
AttributeError: 'list' object has no attribute 'xy'

Process finished with exit code 1
```

**Comment by patmalcolm91** [comment]
Hi Philipp. Can you try it now, with the above commit? The generation of the OBJ seems to work for me without crashing (albeit with lots of warnings), but since the network is so large, opening the resulting OBJ on my computer is nearly impossible. However, if your machine is more powerful, it might work for you.

**Comment by philippwulff** [comment]
Hi Patrick, this is strange. For me, the script crashes with this Error after many UserWarnings:

```
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:518: UserWarning: Unable to generate stop line for short lane gneE103_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/test_data_pw/carla_map_prep/SumoNetVis/Net.py:518: UserWarning: Unable to generate stop line for short lane gneE131_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
IllegalArgumentException: Cannot get offset of single-vertex line
IllegalArgumentException: Cannot get offset of single-vertex line
IllegalArgumentException: Cannot get offset of single-vertex line
IllegalArgumentException: Cannot get offset of single-vertex line
```

**Comment by patmalcolm91** [comment]
I receive the same UserWarnings and the IllegalArgumentExceptions at the end, but the script exits with a zero code and the OBJ file is generated anyway. Is this the case with you?

The IllegalArgumentExceptions appear to be thrown by the underlying geometry engine, and I'm not able to catch them. I will need to instead perform some sort of sanity check on the geometry of each object before processing it. I'm not sure if they have any effect on the validity of the output since I'm unable to open the OBJ file on my computer because of its size. If the script created the OBJ for you, can you try importing it into blender to see if the generated geometry is valid?

**Comment by philippwulff** [comment]
Alright, I see it now. I also could not open the file in Blender on my machine, but tried a trimmed down version of the map and it imported into Blender just fine. Thanks!
